# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
