# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180408_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
